FROM quay.io/centos/centos:stream8
WORKDIR /app
RUN dnf install -y make gcc gcc-c++ git && \
  rm -rf /var/cache/dnf/*
RUN git clone https://github.com/hemajv/whisper.cpp.git . && \
    make
USER root
RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
        https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm \ 
        https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-8.noarch.rpm \
        https://rpmfind.net/linux/centos/8-stream/PowerTools/aarch64/os/Packages/SDL2-2.0.10-2.el8.aarch64.rpm && \
    dnf install -y ffmpeg curl
COPY run.sh /app/
ENTRYPOINT ["sh", "run.sh"]