FROM registry.access.redhat.com/ubi9/python-311:1-77.1726664316

USER root
RUN dnf remove sqlite3 -y && \
    wget https://www.sqlite.org/2023/sqlite-autoconf-3410200.tar.gz && \
    tar -xvzf sqlite-autoconf-3410200.tar.gz && \
    cd sqlite-autoconf-3410200 && \
    ./configure && \
    make && \
    make install && \
    mv /usr/local/bin/sqlite3 /usr/bin/sqlite3 && \
    rm -rf /sqlite-autoconf-3410200*

ENV LD_LIBRARY_PATH="/usr/local/lib"

WORKDIR /rag
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir --upgrade -r /rag/requirements.txt

COPY rag_app.py .
COPY manage_vectordb.py .

EXPOSE 8501

ENV HF_HUB_CACHE=/rag/models/
RUN mkdir -p /rag/models/ && \
    chgrp -R 0 /rag/models/ && \
    chmod -R g=u /rag/models/

ENV OTEL_EXPORTER_OTLP_ENDPOINT="http://127.0.0.1:4317"
ENV OTEL_SERVICE_NAME="rag-demo-app"
ENV OTEL_TRACES_SAMPLER="always_on"

#ENV OTEL_TRACES_SAMPLER="traceidratio"
#ENV OTEL_TRACES_SAMPLER_ARG=0.05  # Sample 5% of traces
ENTRYPOINT ["opentelemetry-instrument", "streamlit", "run", "rag_app.py"]
